services:
  - type: web
    name: vintage-vault
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn 'wsgi:app' --worker-class=eventlet --bind=0.0.0.0:$PORT --workers=1 --timeout=120
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: auction_db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: AWS_REGION
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: BASE_URL
        value: https://vintage-vault-aesv.onrender.com

databases:
  - name: auction_db
    plan: free